export { Login } from "./auth/login/Login";
export { Signup } from "./auth/signUp/Signup";
export { ResetPassword } from "./auth/reset password/ResetPassword";
export { ResetPasswordForm } from "./auth/resetPasswordForm/ResetPasswordForm";
export { About } from "./about/About";
export { Home } from "./home/Home";
export { ReadPost } from "./readPost/ReadPost";
export { Publish } from "./publish/Publish";
export { MyPosts } from "./my posts/MyPosts";
export { PageNotfound } from "./404 page/PageNotfound";
